### ISSUE TITLE
More Customization

### ISSUE THREAD

**Issue by DevDyna** [Modern-Modpacks/kjspkg#17]
I have find that there are somethings that are missing so idk if *there was or not planned:*

### Optional dependencies
> Allow to add optional dependencies on projects

### KJSPKG team / members
> Allow to add more users on same project like team members

**Comment by Gcat101** [comment]
Optional dependencies are planned, but not really in a way you probably have in mind. There will be an additional optional key you can add to .kjspkg where you'd be able to specify a message that shows up whenever someone downloads the script and there you can say which mods/packages you recommend they use with your one.

As for team members, idk what you exactly mean by that. If you mean like multiple authors, the key in .kjspkg is just a string so you can specify the author however you want, I usually do something like `"author": "user1, user2"` whenever I'm working with someone else. If you are talking about changing the script itself, you can just add the person as a contributor to the github repo where the script is stored lol.

**Comment by DevDyna** [comment]
> Optional dependencies are planned, but not really in a way you probably have in mind. There will be an additional optional key you can add to .kjspkg where you'd be able to specify a message that shows up whenever someone downloads the script and there you can say which mods/packages you recommend they use with your one

:thumbsup:

> [...] I usually do something like "author": "user1, user2" whenever I'm working with someone else

I have totally missed it (i will change it)
